# Generated by Django 4.0.6 on 2022-07-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordpress', '0002_rename_blog_poll_rename_blog_poll_answer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='answer',
            new_name='answer1',
        ),
        migrations.AddField(
            model_name='poll',
            name='answer2',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='answer3',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='answer4',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='answer5',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
