# Generated by Django 4.0.6 on 2022-07-05 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordpress', '0003_rename_answer_poll_answer1_poll_answer2_poll_answer3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='answer5',
        ),
    ]
